# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.cache/wt} [current_project]
set_property parent.project_path {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/res/weights.coe}}
add_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/res/00.coe}}
add_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/font.coe}}
add_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_log2_12bit/log2_table_12bit.coe}}
add_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_pow2/pow2_rom.coe}}
read_mem {
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/Users/user/Downloads/ln_table.mem}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/Users/user/Downloads/exp_table.mem}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/font.mem}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/Users/user/Downloads/sin_table_ver_two.mem}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/Users/user/Downloads/tan_table_ver_two.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/Desktop/Oled_Display.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/adder_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/calc_mode_top.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/calculator_mode_output_drawer.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/converter.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/debouncer.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/display_handler.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/divide_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/eh_stream_capture.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/equation_parser.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/error_handling.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/expr_execute_no_check.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/flexible_timer.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/graph_input_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/graph_select_screen.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/grapher_mode.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/grapher_screen_oled.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/key_to_ascii_convertor.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/log2_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/multiply_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/number_parser.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/off_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/oled_keypad.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/parameter_input.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/power_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/precedence_eval.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/pseudo_random_gen.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/quadratic_graph.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/sevenseg_driver.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/shared_equation_buffer.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/sw_debouncer.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/team_alu_bridge.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/imports/new/trigo_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/vga_sync.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/welcome_drawer_oled.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/welcome_drawer_vga.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/welcome_mode_module.v}
  {C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/new/Top_Student.v}
}
read_ip -quiet {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font_ooc.xdc}}]

read_ip -quiet {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_pow2/blk_mem_gen_pow2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_pow2/blk_mem_gen_pow2_ooc.xdc}}]

read_ip -quiet {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_log2_12bit/blk_mem_gen_log2_12bit.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_log2_12bit/blk_mem_gen_log2_12bit_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/constrs_1/new/my_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final_2/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/constrs_1/new/my_constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
