# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/xiang/ee2026_Project/consolidated_sources/constraints/my_constraints.xdc

# IP: ip/divider_generator_0_1/divider_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_generator_0 || ORIG_REF_NAME==divider_generator_0} -quiet] -quiet

# IP: ip/blk_mem_gen_font_2/blk_mem_gen_font.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_font || ORIG_REF_NAME==blk_mem_gen_font} -quiet] -quiet
