# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font.xci
# IP: The module: 'blk_mem_gen_font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_font'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font.xci
# IP: The module: 'blk_mem_gen_font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rkoh2/OneDrive/Desktop/Personal/EE2026_Final/S3_09_RYAN KOH_SEAN LEE_YAO XIANG_YI YANG_Archive.xpr/forryannyy/forryannyy.srcs/sources_1/ip/blk_mem_gen_font/blk_mem_gen_font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_font'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
